### ISSUE TITLE
Some initial story ideas

### ISSUE THREAD

**Issue by vulongphan** [vulongphan/CommLabSoundProject#1]

**Comment by juandapl** [comment]
We need to get:
- a story in 9 parts (each one for a new area)
- those parts can be:
- parts of the story
- riddles

**Comment by juandapl** [comment]
a new approach - **a quest storyline**
1. come up with an order in which the locations should be visited
2. get some kind of questline that drives the user through them
3. that's it

**Comment by juandapl** [comment]
Prince of a Magical Kingdom - he goes to a town where three gemstones are hidden. He needs the three gems to save his kingdom from a dark spell.

He is actually not a prince - the gems are random things he steals from the village. At the end, the user realises he's crazy.

**The Street**
_r1.ogg_ **done**
Narrator/Spirit: The Capital of the Kingdom is in flames. A dark spell has taken over the city, causing hunger and unrest. Only you, Prince, can save us from evil. I'm sending you to a village far in the mountains to collect the three ancient gems of our people. With haste, Prince. We need you. 
Stranger: Wake up! 
(Broom sounds)
Stranger: Oi! Get off my store - you're scaring off the customers. 
User: Please, sir, you have to help me-- our kingdom is in danger. I need to collect the three ancient gemstones!
_r2.ogg_ **done**
Stranger: Rough night? Been there. Alright, just go home.
User: I have to procure a weapon. The kingdom is in danger!
_r3.ogg_ **done**
Stranger: Something's definitely off with your head. I heard the Blacksmith has really good hangover cures though.
User: Yes! A blacksmith! Show me the way!
_r4.ogg_ **done**
Stranger: Go north, to the town square, and then turn left.
(Message pops up - "find the blacksmith")

**Blacksmith**
_r5.ogg_ **done**
Stranger 2: Welcome to the Blacksmith, traveller. How can I help you?
User: Blacksmith, forge me a magical weapon to defeat the forces of darkness.
_r6.ogg_ **done**
Stranger 2: Ah, yeah... I'm actually not the Blacksmith, sorry... Are you okay, dude? You seem beaten up.
Narrator/Spirit: In this village, no one knows of our kingdom. But, don't get distracted, Prince. Follow the path of the gems...
User: Direct me to the Blacksmith, at once!
_r7.ogg_ **done**
Stranger 2: Uh, I know somebody that talks just like you... She lives in a cabin in the forest, across the town square.
(Message pops up - "find the forest")

**Forest gem**
User: Blacksmith! I am here to collect my ancient weapon.
_r8.ogg_ **done**
Crazy old man: I am not the Blacksmith! What even is a Blacksmith?
User: You speak in riddles, Blacksmith. A wise man indeed.
_r9.ogg_ **done**
Crazy old man: And they say I'm crazy. How many times do I need to tell you I'm not the Blacksmith?
User: I come here in search of the gem of my people.
_r10.ogg_ **done**
Crazy old man: Just take this, and leave.
(Paper sounds)
User: The First Gem! And it has an inscription: "Happy hour - south west of the town square"
(Message pops up - "find the happy hour")

**Tavern**
_r11.ogg_ **done**
Narrator/Spirit: This doesn't sound like a place for a Prince. But the gems can be hidden in any place...
Innkeeper: Welcome to The Smelly Ukelele. What can I get you?
User: I come here to find the Second Magical Gem of my kingdom.
_r12.ogg_ **done**
Stranger 3: This man is already gone. Sit down, I'll buy you a beer.
User: I am the Prince of the Kingdom. I do not partake in such vices.
_r13.ogg_ **done**
Innkeeper: What do you think we sell at a tavern? Apples?
User: Apples! I remember what the prophecy said! The Second Gem is hidden in an Apple.
(Message pops up - "find the market and pick up an apple")

**Market gem**
_r14.ogg_ **done**
Narrator/Spirit: You are truly cunning, Prince. Only the greatest minds could have solved that clue. Pick an apple.
Stranger 4: Can you please stop rubbing my apples?
User: Have you seen an exceptionally big apple? One that looks like an ancient gem, maybe?
_r15.ogg_ **done**
Stranger 4: This one. It is the most precious apple I have ever picked - and my most valued posession.
Narrator/Spirit: Stealing is not the way of the enlightened, but the fate of our kingdom depends on it.
User: Tough luck!
_r16.ogg_ **done**
Stranger 4: Somebody get him!
Narrator/Spirit: Run north, as far as you can!
(Message pops up - "run North")

**Cave**
_r17.ogg_ **done**
Miner: Hey, you can't come in here without a hard hat!
User: How dare you speak like that to a Prince?!
_r18.ogg_ **done**
Miner: Where do you think you're going?
Narrator/Spirit: Let's hide here. Keep the gems close to you - the miners can steal them.
Miner: Where did this guy go?
Narrator/Spirit: Night is falling, Prince. You can't stay in this cave. There is a camp west of here - you'll find a place to stay.
(Message pops up - "Find a place to stay")

**Camp gem** 
_r19.ogg_ **done**
Stranger 5: Welcome to Camp Longhorn! Fancy a marshmallow?
User: I'd rather have the freshest game you've hunted today.
_r20.ogg_ **done**
Stranger 5: Then come by the bonfire. We're roasting the biggest wild mini pig ever seen in this forest.
User: So, a regular pig?
_r21.ogg_ **done**
Narrator/Spirit: The prophecies say the last gem shall be earned by a test of fire. This mini pig is too magnificent to be just a coincidence...
User: I'm pretty sure this is a normal pig...
_r22.ogg_ **done**
Narrator/Spirit: There is no time, Prince! A storm is approaching. Grab the animal, and run to the hills!
(Message pops up - "Run west to the hills")

**Hill**
_r23.ogg_ **done**
Crowd (far away): He stole the pig! Find him! Look behind those rocks!
Narrator/Spirit: The prophecies have come true. Put the three gems together, and the kingdom will be saved!
User: Finally... I complete my fate. O Gems, show me the way to save my people!

_r24.ogg_
(paper rumbling sounds)

User: huh?

_r25.ogg_
(paper rumbling sounds)

User: What do I do now?

_r26.ogg_
(paper rumbling sounds)

User: Are you there?

_r27.ogg_
// no feedback from the narrator, a delay of about 2 seconds
// at this time, the crowd, the wind, and the static noise grow louder
